configName: sam_e54_xpro_winc1500
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;core;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_l22;crypto;cryptoauthlib;csp;csp_apps_sam_d11;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_l22;dev_packs;gfx;MPLAB-Harmony-Reference-Apps;net;quick_docs;touch;usb;wireless;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.6.95\atdf\ATSAME54P20A.atdf
